# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tePUgRD6H9g1ZYP1tkd0mJ97rOZFq3CR
"""

from matplotlib.pyplot import *
import random
from scipy.integrate import solve_ivp

#Funcion
def f(a, y):
    return (-1 * a) * y 
#EULER
def euler(f, x, y, h, m):
    a = []
    b = []
    for i in range(m):
        y = y + h*f(x, y)
        x = x + h
        y = round(y, 2)
        x = round(x, 2)
        a += [x]
        b += [y]
    return [a, b]
#REAL
#sol = solve_ivp(f(a,y), [-10, 10], [0,1])
#DATOS INICIALES
m = 100 
a0 = random.randrange(-10,10) 
y0 = random.random()  
#y0 = random.randrange(0,1)  
h = 0.1  # Cantidad para el paso
[x, y] = euler(f, a0, y0, h, m)

#xreal = np.arange(-10,10,0.1)
#yreal= f(xreal,y)
#VALORES DE A / Y
print("el valor de y0 es", y0, "el valor de a0 es", a0 )
#GRAFICA
plot(x, y, "b")
title("Euler")
show()